name: GitHub Profile Snake Animation

on:
  schedule:
    - cron: '*/12 * * * *'  # كل 12 ساعة مثلاً
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3   # مبدّل هنا
        with:
          github_user_name: AhmedGabber  # اسم مستخدم GitHub بتاعك
          outputs: |
            snake.svg?color_snake=00FF00
      - name: Commit Snake
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add snake.svg
          git commit -m "Update Snake animation" || echo "No changes to commit"
          git push
